### ISSUE TITLE
A call to Glfw.GetGamepadState() crashes the program.

### ISSUE THREAD

**Issue by apilatosba** [dcronqvist/DotGLFW#1]
good morning, when i call the Glfw.GetGamepadState() function it crashes the program. this is the error message in the console:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DotGLFW.Glfw.GetGamepadState(Joystick joystick, GamepadState& state)
```

i called this function with a joystick plugged in and without a joystick plugged in, in both cases it crashed.
i checked the source code of Glfw.GetGamepadState() function but couldn't figure out why null reference exception was being thrown. i created a minimal program to demonstrate the issue. this is the link to the repo: https://github.com/apilatosba/DotGLFW.Glfw.GetGamepadState-  

##### Program.cs
```cs
using DotGLFW;
using System;

using static DotGL.GL;

namespace Main {
   class Program {
      static void Main() {
         if (!Glfw.Init()) {
            Console.Error.WriteLine("Failed to initialize GLFW");
            Environment.Exit(1);
         }

         Glfw.SetErrorCallback((errorCode, description) => {
            Console.Error.WriteLine($"GLFW Error: {errorCode} - {description}");
         });

         Glfw.WindowHint(Hint.ContextVersionMajor, GetProjectOpenGLVersionMajor());
         Glfw.WindowHint(Hint.ContextVersionMinor, GetProjectOpenGLVersionMinor());
         Glfw.WindowHint(Hint.OpenGLProfile, OpenGLProfile.CoreProfile);
         Glfw.WindowHint(Hint.Samples, 4);

         Window window = Glfw.CreateWindow(640, 480, "FeelsDankMan", Monitor.NULL, Window.NULL);

         if (window == null) {
            Console.Error.WriteLine("Failed to create GLFW window");
            Glfw.Terminate();
            Environment.Exit(1);
         }

         Glfw.MakeContextCurrent(window);
         Import(Glfw.GetProcAddress);

         // This line crashes the program
         Glfw.GetGamepadState(Joystick.Joystick1, out GamepadState state);

         while (!Glfw.WindowShouldClose(window)) {
            Glfw.PollEvents();
            glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT);

            Glfw.SwapBuffers(window);
         }
      }
   }
}
```

idk if i am missing something very obvious but i would appreciate any feedback from you.
In case it matters, i am on debian12 with x11 windowing system.

**Comment by dcronqvist** [comment]
Hey! Nice find, I don't own a gamepad myself which likely is why this was overlooked, hehe..

**I can reproduce your crashing issue**, and I think I have found a solution, but before I push it, could you please verify that it works as expected and that you get the behaviour you are looking for?

I have crosschecked with one of my other projects which is in C++ (and uses glfw natively) and I am getting identical values for both `DotGLFW` and the other project which makes me think that I may have fixed it.

**What I want you to do**
Replace your (crashing line) `Glfw.GetGamepadState(JoyStick.Joystick1, out GamepadState state);` line with the following snippet
```c#
IntPtr gamepadStatePtr = Marshal.AllocHGlobal(Marshal.SizeOf<GamepadState>());
int getGamepadStateResult = NativeGlfw.GetGamepadState((int)Joystick.Joystick1, out gamepadStatePtr);
GamepadState gamepadState = Marshal.PtrToStructure<GamepadState>(gamepadStatePtr);
if (getGamepadStateResult != 0) 
  Marshal.FreeHGlobal(gamepadStatePtr);
```
The above snippet allocates a GamepadState struct in unmanaged memory which glfw should be able to populate with what you are looking for. Then it marshals it into managed memory and frees the unmanaged pointer, to not leak anything (although on the off chance that it's not able to retrieve the gamepad state, it won't be able to free it properly due to me unfortunately setting that parameter as `out`. So this code is not suitable for actual usage until I have pushed this change)

**How you should verify**
Check that `gamepadState` contains the gamepad state that you are looking for. Since I don't own a gamepad myself, please check with both a gamepad connected and not to see what you get. Please report back with your findings and whether or not this worked for you. If all is well, I'll push a change and bump the version on the NuGet as well - if not, we'll have to keep investigating.

**Comment by apilatosba** [comment]
Thank you for looking into this issue. I am on a one week holiday right now so I can't test if the issue is resolved unfortunately. I can only test it one week later from now, and I will write here again once I do.

**Comment by apilatosba** [comment]
Unfortunately the issue is not resolved. I did what you said and changed Program.cs to 

##### Program.cs
```csharp
using DotGLFW;
using System;
using System.Runtime.InteropServices;

using static DotGL.GL;

namespace Main {
   class Program {
      static void Main() {
         if (!Glfw.Init()) {
            Console.Error.WriteLine("Failed to initialize GLFW");
            Environment.Exit(1);
         }

         Glfw.SetErrorCallback((errorCode, description) => {
            Console.Error.WriteLine($"GLFW Error: {errorCode} - {description}");
         });

         Glfw.WindowHint(Hint.ContextVersionMajor, GetProjectOpenGLVersionMajor());
         Glfw.WindowHint(Hint.ContextVersionMinor, GetProjectOpenGLVersionMinor());
         Glfw.WindowHint(Hint.OpenGLProfile, OpenGLProfile.CoreProfile);
         Glfw.WindowHint(Hint.Samples, 4);

         Window window = Glfw.CreateWindow(640, 480, "FeelsDankMan", Monitor.NULL, Window.NULL);

         if (window == null) {
            Console.Error.WriteLine("Failed to create GLFW window");
            Glfw.Terminate();
            Environment.Exit(1);
         }

         Glfw.MakeContextCurrent(window);
         Import(Glfw.GetProcAddress);

         // This line crashes the program
         // Glfw.GetGamepadState(Joystick.Joystick1, out GamepadState state);

         IntPtr gamepadStatePtr = Marshal.AllocHGlobal(Marshal.SizeOf<GamepadState>());
         int getGamepadStateResult = NativeGlfw.GetGamepadState((int)Joystick.Joystick1, out gamepadStatePtr);
         GamepadState gamepadState = Marshal.PtrToStructure<GamepadState>(gamepadStatePtr);
         if (getGamepadStateResult != 0) 
            Marshal.FreeHGlobal(gamepadStatePtr);

         while (!Glfw.WindowShouldClose(window)) {
            Glfw.PollEvents();
            glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT);

            Glfw.SwapBuffers(window);
         }
      }
   }
}
```

What happens is, I get this exception if a joystick is not plugged in: 
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DotGLFW.Glfw.WindowShouldClose(Window window)
   at Main.Program.Main() in /path/to/project/DotGLFW.Glfw.GetGamepadState-/Main/Program.cs:line 44
```

Program.cs:line 44 is this
`         while (!Glfw.WindowShouldClose(window)) {`

And I get this exception if a joystick is plugged in:
```
Fatal error. Internal CLR error. (0x80131506)
   at DotGLFW.Glfw.WindowShouldClose(DotGLFW.Window)
   at Main.Program.Main()
```

I also want to note here that program runs fine if I comment out the snippet you suggested.

To test even further, I tried to fetch gamepadState before this line `while (!Glfw.WindowShouldClose(window)) {` and changed Program.cs file to

##### Program.cs
```csharp
using DotGLFW;
using System;
using System.Runtime.InteropServices;

using static DotGL.GL;

namespace Main {
   class Program {
      static void Main() {
         if (!Glfw.Init()) {
            Console.Error.WriteLine("Failed to initialize GLFW");
            Environment.Exit(1);
         }

         Glfw.SetErrorCallback((errorCode, description) => {
            Console.Error.WriteLine($"GLFW Error: {errorCode} - {description}");
         });

         Glfw.WindowHint(Hint.ContextVersionMajor, GetProjectOpenGLVersionMajor());
         Glfw.WindowHint(Hint.ContextVersionMinor, GetProjectOpenGLVersionMinor());
         Glfw.WindowHint(Hint.OpenGLProfile, OpenGLProfile.CoreProfile);
         Glfw.WindowHint(Hint.Samples, 4);

         Window window = Glfw.CreateWindow(640, 480, "FeelsDankMan", Monitor.NULL, Window.NULL);

         if (window == null) {
            Console.Error.WriteLine("Failed to create GLFW window");
            Glfw.Terminate();
            Environment.Exit(1);
         }

         Glfw.MakeContextCurrent(window);
         Import(Glfw.GetProcAddress);

         // This line crashes the program
         // Glfw.GetGamepadState(Joystick.Joystick1, out GamepadState state);

         IntPtr gamepadStatePtr = Marshal.AllocHGlobal(Marshal.SizeOf<GamepadState>());
         int getGamepadStateResult = NativeGlfw.GetGamepadState((int)Joystick.Joystick1, out gamepadStatePtr);
         GamepadState gamepadState = Marshal.PtrToStructure<GamepadState>(gamepadStatePtr);
         if (getGamepadStateResult != 0) 
            Marshal.FreeHGlobal(gamepadStatePtr);

         Console.WriteLine(gamepadState.GetButtonState(GamepadButton.Cross));

         while (!Glfw.WindowShouldClose(window)) {
            Glfw.PollEvents();
            glClearColor(0.2f, 0.3f, 0.3f, 1.0f);
            glClear(GL_COLOR_BUFFER_BIT);

            Glfw.SwapBuffers(window);
         }
      }
   }
}
```

In this case what happens is, I get this exception if a joystick is not plugged in:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Main.Program.Main() in /path/to/project/DotGLFW.Glfw.GetGamepadState-/Main/Program.cs:line 44
```

In this case, Program.cs:line 44 is this (I think you guessed it):
`         Console.WriteLine(gamepadState.GetButtonState(GamepadButton.Cross));`

And I get this exception if a joystick is plugged in:
```
Fatal error. Internal CLR error. (0x80131506)
   at Main.Program.Main()
```

**Comment by dcronqvist** [comment]
Hi again! thank you for your extensive investigation on this, very impressive!

After having looked at your results and report here, I've pushed a change and bumped the version on nuget (1.0.3). Please bump your version in your .csproj and attempt to call `Glfw.GetGamepadState(Joystick.Joystick1, out GamepadState state);` as you did initially. 

Please check if it works.

**Comment by apilatosba** [comment]
now it works. thank you.

**Comment by dcronqvist** [comment]
Great! Thanks for your contribution, friend! :)
